/* global $lang */
var $Zhibiao = {
  avg_resp_time: { name: $lang('highcharts.responseTime'), dw: 'ms' },
  error_calls: { name: $lang('highcharts.errorNumber'), dw: $lang('highcharts.times') },
  sum_resp_time: { name: $lang('highcharts.totalResponseTime'), dw: 'ms' },
  max_resp_time: { name: $lang('highcharts.maximumResponseTime'), dw: 'ms' },
  min_resp_time: { name: $lang('highcharts.minimumResponseTime'), dw: 'ms' },
  mid_resp_time: { name: $lang('highcharts.medianresponsetime'), dw: 'ms' },
  request_count: { name: $lang('highcharts.requestNumbers'), dw: $lang('highcharts.times') },
  avgTimeLine: { name: $lang('highcharts.requestNumbers'), dw: $lang('highcharts.times') },
  request_num: { name: $lang('highcharts.requestNumbers'), dw: $lang('highcharts.times') },
  throughput: { name: $lang('highcharts.requestNumber'), dw: $lang('highcharts.times') },
  m_error_calls: { name: $lang('highcharts.errorNumberPerMinute'), dw: $lang('highcharts.times') },
  slow_calls: { name: $lang('highcharts.slowerrequests'), dw: $lang('highcharts.times') },
  slow_calls_rate: { name: $lang('highcharts.slowerrequestratio'), dw: '%' },
  very_slow_calls: { name: $lang('highcharts.slowrequests'), dw: $lang('highcharts.times') },
  very_slow_calls_rate: { name: $lang('highcharts.slowrequestratio'), dw: '%' },
  stall_slow_calls: { name: $lang('highcharts.stagnationrequests'), dw: $lang('highcharts.times') },
  stall_slow_calls_rate: { name: $lang('highcharts.stagnationrequestratio'), dw: '%' },
  avg_cpu_time: { name: $lang('highcharts.cpuAverageTime'), dw: 'ms' },
  httpErrorCount: { name: $lang('highcharts.errorRequestNumber'), dw: $lang('highcharts.times') },
  http_error_rate: { name: $lang('highcharts.requesterrorrates'), dw: '%' },
  m_http_error_count: { name: $lang('highcharts.requestsperminuteerrorcount'), dw: $lang('highcharts.times') },
  heap_commited: { name: $lang('highcharts.heapMemorySubmittedsize'), dw: 'MB' },
  heap_available: { name: $lang('highcharts.heapMemoryMaximumAvailable'), dw: 'MB' },
  heap_usage_rate: { name: $lang('highcharts.heapMemoryUsageRate'), dw: '%' },
  heapUseSize: { name: $lang('highcharts.heapMemoryUsage'), dw: 'MB' },
  heapCommittedSize: { name: $lang('highcharts.committedHeapMemory'), dw: 'MB' },
  maxHeapSize: { name: $lang('highcharts.maxHeapMemory'), dw: 'MB' },
  m_gc_time: { name: $lang('highcharts.gcTimeUsagePerMinute'), dw: 'ms' },
  m_major_count: { name: $lang('highcharts.majorCollectionNumberPerMinute'), dw: $lang('highcharts.times') },
  m_minor_count: { name: $lang('highcharts.minorCollectionNumberPerMinute'), dw: $lang('highcharts.times') },
  m_gc_number: { name: $lang('highcharts.GCNumberPerMinute'), dw: $lang('highcharts.times') },
  running_threads: { name: $lang('highcharts.theaveragenumberofthreads'), dw: $lang('highcharts.a') },
  deadlock_threads: { name: $lang('highcharts.deadlocknumberofthreads'), dw: $lang('highcharts.a') },
  cur_loaded_classes: { name: $lang('highcharts.thenumberofaverageloadingclass'), dw: $lang('highcharts.a') },
  total_loaded_classes: { name: $lang('highcharts.thetotalnumberofloadingaclass'), dw: $lang('highcharts.a') },
  cpu_usage: { name: $lang('highcharts.CPUUsageRate'), dw: '%' },
  cpu_idle: { name: 'CPU idle', dw: '' },
  s_disk_read_bytes_kb: { name: $lang('highcharts.diskReadSizePerSecond'), dw: 'KB' },
  s_disk_read_count: { name: $lang('highcharts.diskReadNumberPerSecond'), dw: $lang('highcharts.times') },
  s_disk_write_bytes_kb: { name: $lang('highcharts.diskWriteSizePerSecond'), dw: 'KB' },
  s_disk_write_count: { name: $lang('highcharts.diskWriteNumberPerSecond'), dw: $lang('highcharts.times') },
  s_net_recv_bytes_kb: { name: $lang('highcharts.networkIncomingSizePerSecond'), dw: 'KB' },
  s_net_recv_packages: { name: $lang('highcharts.networkIncomingPacketsPerSecond'), dw: $lang('highcharts.a') },
  s_net_send_bytes_kb: { name: $lang('highcharts.networkOutgoingSizePerSecond'), dw: 'KB' },
  s_net_send_packages: { name: $lang('highcharts.networkOutgoingPacketsPerSecond'), dw: $lang('highcharts.a') },
  mem_size: { name: $lang('highcharts.totalmemorysize'), dw: 'MB' },
  used_mem_size: { name: $lang('highcharts.memoryusagesize'), dw: 'MB' },
  used_mem_rate: { name: $lang('highcharts.memoryuseof'), dw: '%' },
  tcp_conn_count: { name: $lang('highcharts.currentTCPConnectionNumber'), dw: $lang('highcharts.a') },
  max_conn_count: { name: $lang('highcharts.maximumTCPConnectionNumber'), dw: $lang('highcharts.a') },
  avg_conn_count: { name: $lang('highcharts.averageTCPConnectionNumber'), dw: $lang('highcharts.a') },
  cur_open_fds: { name: $lang('highcharts.currentFileOpeningNumber'), dw: $lang('highcharts.a') },
  max_open_fds: { name: $lang('highcharts.maximumFileOpeningNumber'), dw: $lang('highcharts.a') },
  avg_open_fds: { name: $lang('highcharts.averageFileOpeningNumber'), dw: $lang('highcharts.a') },
  free_disk_size: { name: $lang('highcharts.freediskspace'), dw: 'MB' },
  free_disk_rate: { name: $lang('highcharts.freediskspaceof'), dw: '%' },
  used_disk_size: { name: $lang('highcharts.partitionusedspace'), dw: 'GB' },
  used_disk_rate: { name: $lang('highcharts.partitionofusedspaceaccounted'), dw: '%' },
  free_mem_size: { name: $lang('highcharts.freememorysize'), dw: 'MB' },
  free_mem_rate: { name: $lang('highcharts.accountsforfreememorythan'), dw: '%' },
  allexception_count: { name: $lang('highcharts.abnormalNumber'), dw: $lang('highcharts.a') },
  m_allexception_count: { name: $lang('highcharts.abnormalnumberperminute'), dw: $lang('highcharts.a') },
  call_time: { name: $lang('highcharts.callTime'), dw: 'ms' },
  avg_call_time: { name: $lang('highcharts.averageCallTime'), dw: 'ms' },
  max_call_time: { name: $lang('highcharts.maximumCallTime'), dw: 'ms' },
  min_call_time: { name: $lang('highcharts.minimumCallTime'), dw: 'ms' },
  call_count: { name: $lang('highcharts.callNumber'), dw: $lang('highcharts.times') },
  m_call_count: { name: $lang('highcharts.everyminuteofcalls'), dw: $lang('highcharts.times') },
  m_call_err_count: { name: $lang('highcharts.everyminutecallwrongnumber'), dw: $lang('highcharts.times') },
  errorCalls: { name: $lang('highcharts.errorNumber'), dw: $lang('highcharts.times') },
  minuteErrorCount: { name: $lang('highcharts.requestsPerMinute'), dw: $lang('highcharts.times') },
  avg_request_time: { name: $lang('highcharts.averageResponseTime'), dw: 'ms' },
  error_request: { name: $lang('highcharts.errornumber'), dw: $lang('highcharts.times') },
  error_rate: { name: $lang('highcharts.errorRate'), dw: '%' },
  healthCalls: { name: $lang('highcharts.healthy'), dw: $lang('highcharts.times') },
  unhealthy_sum_num: { name: $lang('highcharts.unhealthy'), dw: $lang('highcharts.times') },
  verySlowCalls: { name: $lang('highcharts.verySlow'), dw: $lang('highcharts.times') },
  stallSlowCalls: { name: $lang('highcharts.stalled'), dw: $lang('highcharts.times') },
  slowCalls: { name: $lang('highcharts.slow'), dw: $lang('highcharts.times') },
  maxRespTime: { name: $lang('highcharts.max'), dw: 'ms' },
  minuteRespTime: { name: $lang('highcharts.requestsPerMinute'), dw: $lang('highcharts.times') },
  sumErrorNum: { name: $lang('highcharts.errorNumber'), dw: $lang('highcharts.times') },
  sumNum: { name: $lang('highcharts.requestNumber'), dw: $lang('highcharts.times') },
  minuteRequestCount: { name: $lang('highcharts.requestNumber'), dw: $lang('highcharts.times') },
  sum_num: { name: $lang('highcharts.callTime'), dw: 'ms' },
  verySlowNum: { name: $lang('highcharts.verySlowRequest'), dw: $lang('highcharts.times') },
  stallNum: { name: $lang('highcharts.stalledRequest'), dw: $lang('highcharts.times') },
  running_threads_count: { name: 'Running', dw: $lang('highcharts.a') },
  deadlockThreadsCount: { name: 'Deadlock', dw: $lang('highcharts.a') },
  blockThreadsCount: { name: 'Block', dw: $lang('highcharts.a') },
  finish_threads_count: { name: 'Finish', dw: $lang('highcharts.a') },
  maxTime: { name: $lang('highcharts.maximumResponseTime'), dw: 'ms' },
  mem_usage: { name: $lang('highcharts.memoryUsageRate'), dw: '%' },
  diskio_read_velocity: { name: $lang('highcharts.diskreadspeed'), dw: 'KB/s' },
  diskio_write_velocity: { name: $lang('highcharts.thediskwritespeed'), dw: 'KB/s' },
  net_send_velocity: { name: $lang('highcharts.networkspeed'), dw: 'KB/s' },
  net_recv_velocity: { name: $lang('highcharts.receptionnetwork'), dw: 'KB/s' },
  tcpListenCount: { name: 'Listen', dw: $lang('highcharts.a') },
  tcpEstablishedCount: { name: 'Establish', dw: $lang('highcharts.a') },
  tcpTimeWaitCount: { name: 'TimeWait', dw: $lang('highcharts.a') },
  tcpFinWaitCount: { name: 'FinWait', dw: $lang('highcharts.a') },
  tcpFinWait2Count: { name: 'FinWait2', dw: $lang('highcharts.a') },
  tcpCloseWaitCount: { name: 'CloseWait', dw: $lang('highcharts.a') },
  cpu_usage_percent: { name: 'CPU', dw: '%' },
  mem_usage_percent: { name: $lang('highcharts.memory'), dw: '%' },
  disk_usage_percent: { name: $lang('highcharts.disk'), dw: '%' },
  disk_usage: { name: $lang('highcharts.partitionusedspaceof'), dw: '%' },
  runningThreadsCount: { name: $lang('highcharts.numberOfRunningThreads'), dw: $lang('highcharts.a') },
  gcTimePerminute: { name: $lang('highcharts.gcTime'), dw: 'ms' },
  majorGcTimePerminute: { name: 'Major Collections', dw: 'ms' },
  minorGcTimePerminute: { name: 'Minor Collections', dw: 'ms' },
  minorGcCount: { name: $lang('highcharts.MinorGCNumber'), dw: $lang('highcharts.times') },
  majorGcCount: { name: $lang('highcharts.MajorGCNumber'), dw: $lang('highcharts.times') },
  gen0Count: { name: $lang('highcharts.gcNumber'), dw: $lang('highcharts.times') },
  gen1Count: { name: $lang('highcharts.gcNumber'), dw: $lang('highcharts.times') },
  gen2Count: { name: $lang('highcharts.gcNumber'), dw: $lang('highcharts.times') },
  alreadyLoad: { name: $lang('highcharts.loaded'), dw: $lang('highcharts.a') },
  already_load: { name: $lang('highcharts.loaded'), dw: $lang('highcharts.a') },
  alreadyUnload: { name: $lang('highcharts.uninstall'), dw: $lang('highcharts.a') },
  totalLoaded: { name: $lang('highcharts.atotalloading'), dw: $lang('highcharts.a') },
  current_file_open: { name: $lang('highcharts.fileOpeningNumber'), dw: $lang('highcharts.a') },
  gc_time_perminute_csharp: { name: $lang('highcharts.gcTime'), dw: 'ms/min' },
  gen0UseSize: { name: $lang('highcharts.gen0Usage'), dw: 'MB' },
  gen1UseSize: { name: $lang('highcharts.gen1Usage'), dw: 'MB' },
  gen2UseSize: { name: $lang('highcharts.gen2Usage'), dw: 'MB' },
  genLargeObjUseSize: { name: $lang('highcharts.genLargeObjUsage'), dw: 'MB' },
  internalName: { name: $lang('highcharts.businessTransactionsPath'), dw: '' },
  internal_name: { name: $lang('highcharts.businessTransactionsPath'), dw: '' },
  alias: { name: $lang('highcharts.businessTransactionsAlias'), dw: '' },
  sumResp: { name: $lang('highcharts.requestNumber'), dw: $lang('highcharts.times') },
  maxTimeLine: { name: $lang('highcharts.max'), dw: 'ms' },
  exceptionCount: { name: $lang('highcharts.abnormalNumber'), dw: $lang('highcharts.a') },
  perm_gen_use: { name: 'Young Generation', dw: 'MB' },
  old_gen_use: { name: 'Old Generation', dw: 'MB' },
  young_gen_use: { name: 'Young Generation', dw: 'MB' },
  survivior_space_use: { name: 'Survivior Space', dw: 'MB' },
  sumErrorResp: { name: $lang('chartEngine.Wrongnumber'), dw: $lang('highcharts.times') },
  respTime: { name: $lang('highcharts.responseTime'), dw: 'ms' },
  sqlDetail: { name: $lang('highcharts.calladdress'), dw: '' },
  code_cache_use: { name: 'Code Cache', dw: 'MB' },
  ps_eden_space_use: { name: 'Ps Eden Space', dw: 'MB' },
  ps_old_gen_use: { name: 'Ps Old Gen', dw: 'MB' },
  ps_perm_gen_use: { name: 'Ps Perm Gen', dw: 'MB' },
  ps_survivor_space_use: { name: 'Ps Survivor Space', dw: 'MB' },
  meta_space_use: { name: 'Meta Space', dw: 'MB' },
  compressed_space_use: { name: 'Compressed Space', dw: 'MB' },
  partition_name: { name: $lang('highcharts.partitionname'), dw: '' },
  be_resp_time: { name: $lang('highcharts.calltakes'), dw: 'ms' },
  be_request_count: { name: $lang('highcharts.requestNumber'), dw: $lang('highcharts.times') },
  be_error_calls: { name: $lang('chartEngine.Wrongnumber'), dw: $lang('highcharts.times') },
  currentActiveConn: { name: $lang('highcharts.takeupthenumberofconnections'), dw: $lang('highcharts.a') },
  currentInactiveConn: { name: $lang('highcharts.freeconnectionnumberPool'), dw: $lang('highcharts.a') },
  currentFreeConn: { name: $lang('highcharts.freeconnectionnumberPool'), dw: $lang('highcharts.a') },
  currentPoolSize: { name: $lang('highcharts.totalnumberofconnections'), dw: $lang('highcharts.a') },
  currentPoolSizeMax: { name: $lang('highcharts.maxofconnections'), dw: $lang('highcharts.a') },
  currentWaitSize: { name: $lang('highcharts.blockingconnections'), dw: $lang('highcharts.a') },
  diskio_read_count: { name: $lang('highcharts.numberofdiskread'), dw: $lang('highcharts.timescalls') + '/' + $lang('highcharts.second') },
  diskio_write_count: { name: $lang('highcharts.numberofdiskwrites'), dw: $lang('highcharts.timescalls') + '/' + $lang('highcharts.second') },
  net_recv_packages: { name: $lang('highcharts.networkreceivespackets'), dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  net_send_packages: { name: $lang('highcharts.networktosendpackets'), dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  rate: { name: $lang('highcharts.diskUsageRate'), dw: '%' },
  'B_Read_sec_cur_val': { name: $lang('highcharts.diskreadspeed'), dw: 'KB/s' },
  'B_Write_sec_cur_val': { name: $lang('highcharts.thediskwritespeed'), dw: 'KB/s' },
  'Reads_sec_cur_val': { name: $lang('highcharts.numberofdiskread'), dw: $lang('highcharts.timescalls') + '/' + $lang('highcharts.second') },
  'Writes_sec_cur_val': { name: $lang('highcharts.numberofdiskwrites'), dw: $lang('highcharts.timescalls') + '/' + $lang('highcharts.second') },
  'Outgoing_Carrie_cur_val': { name: 'Carrier', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Outgoing_Collisions_cur_val': { name: 'Collisions', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Outgoing_Dropped_cur_val': { name: 'Dropped', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Outgoing_Errors_cur_val': { name: 'Error', dw: $lang('highcharts.aaErrors') + '/' + $lang('highcharts.second') },
  'Outgoing_Overruns_cur_val': { name: 'Overruns', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Outgoing_Packets_cur_val': { name: $lang('highcharts.sendingPacketsNumber'), dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Incoming_Dropped_cur_val': { name: 'Dropped', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Incoming_Errors_cur_val': { name: 'Error', dw: $lang('highcharts.aaErrors') + '/' + $lang('highcharts.second') },
  'Incoming_Frame_cur_val': { name: 'Frame', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Incoming_Overruns_cur_val': { name: 'Overruns', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Incoming_Packets_cur_val': { name: $lang('highcharts.receivingPacketsNubmer'), dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  'Incoming_B_cur_val': { name: $lang('highcharts.receivingPacketsNubmer'), dw: 'KB/s' },
  'Outgoing_B_cur_val': { name: $lang('highcharts.sendingPacketsNumber'), dw: 'KB/s' },
  'CPU_cur_val': { name: $lang('highcharts.CPUUsageRate'), dw: '％' },
  'Memory_cur_val': { name: $lang('highcharts.memoryUsageRate'), dw: '%' },
  healthyNum: { name: $lang('highcharts.healthofcalls'), dw: $lang('highcharts.times'), legend: $lang('highcharts.healthcallnumberandproportion') },
  slowNum: { name: $lang('highcharts.slowcallnumber'), dw: $lang('highcharts.times'), legend: $lang('highcharts.slowcallnumberandproportion') },
  useRate: { name: $lang('highcharts.diskOccupancyRate'), dw: '%' },
  ioUseRate: { name: $lang('highcharts.diskIOUsageRate'), dw: '%' },
  ioReads: { name: $lang('highcharts.numberofdiskread'), dw: $lang('highcharts.timescalls') + '/' + $lang('highcharts.second') },
  ioWrites: { name: $lang('highcharts.numberofdiskwrites'), dw: $lang('highcharts.timescalls') + '/' + $lang('highcharts.second') },
  readSpeed: { name: $lang('highcharts.diskreadspeed'), dw: 'MB/s' },
  writeSpeed: { name: $lang('highcharts.thediskwritespeed'), dw: 'MB/s' },
  readSize: { name: $lang('highcharts.diskReading'), dw: 'MB' },
  writeSize: { name: $lang('highcharts.diskWriting'), dw: 'MB' },
  avgHostRate: { name: $lang('highcharts.hostAvailability'), dw: '%' },
  cpuUsageRate: { name: $lang('highcharts.CPUUsageRate'), dw: '%' },
  memUsageRate: { name: $lang('highcharts.memoryUsageRate'), dw: '%' },
  averageLoadLast1MinSum: { name: 'Load Average-1 min', dw: '' },
  averageLoadLast5MinSum: { name: 'Load Average-5 mins', dw: '' },
  averageLoadLast15MinSum: { name: 'Load Average-15 mins', dw: '' },
  txPackets: { name: 'TX packets', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  txErrors: { name: 'Errors', dw: $lang('highcharts.aaErrors') + '/' + $lang('highcharts.second') },
  txDrops: { name: 'Dropped', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  txOverruns: { name: 'Overruns', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  txCarrier: { name: 'Carrier', dw: $lang('highcharts.aacalls') + $lang('highcharts.second') },
  txCollisions: { name: 'Collisions', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  rxPackets: { name: 'RX packets', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  rxErrors: { name: 'Errors', dw: $lang('highcharts.aaErrors') + '/' + $lang('highcharts.second') },
  rxDrops: { name: 'Dropped', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  rxOverruns: { name: 'Overruns', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  rxFrame: { name: 'Frame', dw: $lang('highcharts.aacalls') + '/' + $lang('highcharts.second') },
  txBytes: { name: 'TX bytes', dw: 'KB/s' },
  rxBytes: { name: 'RX bytes', dw: 'KB/s' },
  cpuUsageTotalSum: { name: 'Total', dw: '%' },
  cpuUsageSysSum: { name: 'System', dw: '%' },
  cpuUsageUserSum: { name: 'User', dw: '%' },
  cpuUsageStolenSum: { name: 'Stolen', dw: '%' },
  cpuUsageIowaitSum: { name: 'IOWait', dw: '%' },
  memUseCount: { name: $lang('highcharts.memoryUsage'), dw: 'MB' },
  swapUseCount: { name: $lang('highcharts.swapUsage'), dw: 'MB' },
  fileOpenCount: { name: $lang('highcharts.fileOpeningNumber'), dw: $lang('highcharts.a') },
  baseLine: { name: $lang('highcharts.dynamicBaseline'), dw: 'ms' },
  rBaseLine: { name: $lang('highcharts.dynamicBaseline'), dw: $lang('highcharts.requestsMin') },
  responseTime: { name: $lang('highcharts.averageResponseTime'), dw: 'ms' },
  slowRate: { name: $lang('highcharts.slowspeed'), dw: '%' },
  throughputRate: { name: $lang('highcharts.throughputRate'), dw: 'rpm' },
  cupUsage: { name: $lang('highcharts.CPUUsageRate'), dw: '%' },
  cpuUsage: { name: $lang('highcharts.CPUUsageRate'), dw: '%' },
  memUsage: { name: $lang('highcharts.memoryUsageRate'), dw: '%' },
  diskUsage: { name: $lang('highcharts.diskUsage'), dw: '%' },
  heapUsage: { name: $lang('highcharts.heapUsageRate'), dw: '%' },
  deadlockThreads: { name: $lang('highcharts.numberOfDeadlockThreads'), dw: '' },
  averageCount: { name: $lang('highcharts.averageResponseTime'), dw: 'ms' },
  avgRequestTime: { name: $lang('highcharts.averageResponseTime'), dw: 'ms' },
  reqCount: { name: $lang('highcharts.requestNumber'), dw: $lang('highcharts.times') },
  errCount: { name: $lang('highcharts.errorNumber'), dw: $lang('highcharts.times') },
  activeCount: { name: $lang('highcharts.takeupthenumberofconnections'), dw: $lang('highcharts.a') },
  freeCount: { name: $lang('highcharts.freeconnectionnumber'), dw: $lang('highcharts.a') },
  sumCount: { name: $lang('highcharts.totalnumberofconnections'), dw: $lang('highcharts.a') },
  sqldetail: { name: $lang('highcharts.calladdress'), dw: '' },
  avgRespTime: { name: $lang('highcharts.avgRespTime'), dw: 'ms' },
  quantile: { name: $lang('highcharts.fifty'), dw: 'ms' },
  quantile75: { name: $lang('highcharts.seventyFive'), dw: 'ms' },
  quantile95: { name: $lang('highcharts.ninetyFive'), dw: 'ms' },
  quantile99: { name: $lang('highcharts.ninetyNine'), dw: 'ms' },
  count0_perminute: { name: 'Gen0GC', dw: $lang('highcharts.times') },
  count1_perminute: { name: 'Gen1GC', dw: $lang('highcharts.times') },
  count2_perminute: { name: 'Gen2GC', dw: $lang('highcharts.times') }
}
